apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-data
            readOnly: true
      volumes:
        - name: nginx-data
          configMap:
           name: nginx-data
           items:
             - key: index.html
               path: index.html
          

